### ISSUE TITLE
'Error in `left_join()`: ! Join columns must be present in data. ✖ Problem with `urlSeasonBREF`.

### ISSUE THREAD

**Issue by iyaweheze** [abresler/nbastatR#109]
I am having an issue using this package. When I run this example 'bref_teams_stats(seasons = 2017:2018)' I keep receiving the error 

'Error in `left_join()`:
! Join columns must be present in data.
✖ Problem with `urlSeasonBREF`.

When I run this one 'bref_players_stats(seasons = 2017:2018, tables = c("advanced", "totals"))' I receive the error

'Error in `mutate()`:
! Problem while computing `yearSeason = slugSeason %>% substr(1,
  4) %>% as.numeric() + 1`.
Caused by error in `substr()`:
! object 'slugSeason' not found'.

**Comment by mtkearney** [comment]
same issue for bref_players_stats

**Comment by iyaweheze** [comment]
> same issue for bref_players_stats

I think these errors could be due to basketball-reference temporarily banning you because of rate limits. I got around this issue by limiting how often I pulled info from the site.

**Comment by mpardo92** [comment]
Did you ever figure out around this? I'm getting similar errors -(even after uninstalling the package/R and re-installing).

**Comment by lewispipkin** [comment]
Per https://www.basketball-reference.com/robots.txt the crawl delay is now 3 seconds (maybe it was before, too, but they've started enforcing it heavily). Throw in a Sys.sleep(3) between each call and you should be fine, that's been working for me.

**Comment by mpardo92** [comment]
It's been 2 days now since this error and nothing has worked including the Sys.sleep(3)... any suggestions

**Comment by abresler** [comment]
I am no longer developing this package so I would look elsewhere or fork the package and try to figure it out yourself.
