### ISSUE TITLE
Updated R and RStudio, redownloaded packages and now receiving error messages about deprecation. Unable to call functions. 

### ISSUE THREAD

**Issue by mpardo92** [abresler/nbastatR#111]
Hi there, not sure what's going on but I am unable to make calls using the package... Here's the error messages I receive. 

######

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

######

today <- current_schedule() %>% filter(dateGame == Sys.Date()) %>% rename(Team = slugTeamHome, opp_team = slugTeamAway) %>% select(Team, opp_team) %>% mutate(Stadium = "Home")
Warning message:                                                                                                                    
`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
ℹ The deprecated feature was likely used in the nbastatR package.
  Please report the issue at <https://github.com/abresler/nbastatR/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

#####

players <- bref_players_stats(seasons = 2016:2023, tables = c("advanced")) %>% select(namePlayer, groupPosition, slugPosition, ratioPER, pctUSG, idPlayerNBA) %>% 
rename(Player = namePlayer, Position = groupPosition, ID = idPlayerNBA, Positions = slugPosition)

parsed http://www.basketball-reference.com/leagues/NBA_2016_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2017_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2018_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2019_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2020_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2021_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2022_advanced.html
parsed http://www.basketball-reference.com/leagues/NBA_2023_advanced.html

Error in `mutate()`:
ℹ In argument: `yearSeason = slugSeason %>% substr(1, 4) %>% as.numeric() + 1`.
Caused by error in `substr()`:
! object 'slugSeason' not found

######

logs22 <- game_logs(seasons = 2016:2023, result_types = c("player")) %>% 
rename(Season = slugSeason, League = slugLeague, Season_Type = typeSeason, Date = dateGame, team = nameTeam, Game_Location = locationGame, Matchup = slugMatchup, Team = slugTeam, opp_team = slugOpponent, Game_Outcome = outcomeGame, Player = namePlayer, ID = idPlayer)

Acquiring NBA basic player game logs for the 2015-16 Regular Season
Acquiring NBA basic player game logs for the 2016-17 Regular Season                                                                 
Acquiring NBA basic player game logs for the 2017-18 Regular Season
Acquiring NBA basic player game logs for the 2018-19 Regular Season
Acquiring NBA basic player game logs for the 2019-20 Regular Season
Acquiring NBA basic player game logs for the 2020-21 Regular Season
Acquiring NBA basic player game logs for the 2021-22 Regular Season
Acquiring NBA basic player game logs for the 2022-23 Regular Season

Warning messages:
1: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
ℹ Using compatibility `.name_repair`.
ℹ The deprecated feature was likely used in the nbastatR package.
  Please report the issue at <https://github.com/abresler/nbastatR/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
2: Supplying `...` without names was deprecated in tidyr 1.0.0.
ℹ Please specify a name for each selection.
ℹ Did you want `data = -c(slugLeague, typeResult, slugSeason, yearSeason)`?
ℹ The deprecated feature was likely used in the nbastatR package.
  Please report the issue at <https://github.com/abresler/nbastatR/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
3: `cols` is now required when using `unnest()`.
ℹ Please use `cols = c(dataTables)`.

**Comment by travisbarrick** [comment]
I also updated packages and am now getting errors. I'm not sure how related it is to the issue above, but when I try to get a simple box score I'm getting the error below.

box_scores(game_ids = c(21700002, 21700003), box_score_types = c("Traditional"), result_types = c("player"), assign_to_environment = TRUE, return_message = TRUE)
Getting NBA player Traditional box score for game 21700002
Getting NBA player Traditional box score for game 21700003
# A tibble: 0 × 0
Warning messages:
1: Unknown or uninitialised column: `typeResult`. 
2: Unknown or uninitialised column: `typeResult`.

**Comment by abresler** [comment]
I am no longer developing this package.  I would encourage you to look elsewhere or fork it and try to figure it out on your own.
