### ISSUE TITLE
bref_teams_stats(seasons = 2019) not working

### ISSUE THREAD

**Issue by anthonypiccolo** [abresler/nbastatR#15]
For some reason it's not working, anything that's not from bref seems to work fine though. Any ideas?

`> bref_teams_stats(seasons = 2019)
Parsing https://www.basketball-reference.com/leagues/NBA_2019.html
Error: `by` required, because the data sources have no common variables
Call `rlang::last_error()` to see a backtrace`

`> rlang::last_error()
<error>
message: `by` required, because the data sources have no common variables
class:   `rlang_error`
backtrace:
 -nbastatR::bref_teams_stats(seasons = 2019)
 -dplyr::left_join(., df_urls)
 -dplyr:::common_by.NULL(by, x, y)
 -dplyr:::bad_args("by", "required, because the data sources have no common variables")
 -dplyr:::glubort(fmt_args(args), ..., .envir = .envir)
Call `summary(rlang::last_error())` to see the full backtrace`

**Comment by abresler** [comment]
Works for me -- update all your packages and then reinstall nbastatR
