### ISSUE TITLE
bref_team_stats(seasons =2017) not working

### ISSUE THREAD

**Issue by fullcourt** [abresler/nbastatR#16]
The function seems to be working for all other years but for some reason not getting any data from the 2016-17 season. 

`<error>
message: `by` required, because the data sources have no common variables
class:   `rlang_error`
fields:  `message`, `trace` and `parent`
backtrace:
█
└─nbastatR::bref_teams_stats(2017)
  └─`%>%`(...)
    ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
    └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
      └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
        └─nbastatR:::`_fseq`(`_lhs`)
          └─magrittr::freduce(value, `_function_list`)
            └─function_list[[i]](value)
              ├─dplyr::left_join(., df_urls)
              └─dplyr:::left_join.tbl_df(., df_urls)
                ├─dplyr::common_by(by, x, y)
                └─dplyr:::common_by.NULL(by, x, y)
                  └─dplyr:::bad_args("by", "required, because the data sources have no common variables")
                    └─dplyr:::glubort(fmt_args(args), ..., .envir = .envir)`

**Comment by abresler** [comment]
Reinstall the newest version

**Comment by fullcourt** [comment]
Thanks!
