### ISSUE TITLE
bref_team_stats(seasons =2018) not working

### ISSUE THREAD

**Issue by tonyelhabr** [abresler/nbastatR#17]
It looks like the site added a Net Rating column for the 2018 season in the Miscellaneous Stats table (and not for previous seasons), which causes `bref_team_stats(seasons = 2018)` to fail for me. (The error that is returned for me is `"Error in select_impl(.data, vars) : Column `28` cannot have NA as name"`.) From browsing the source code, it looks like this may be due to `actual_names` in `.parse.bref.team.misc()` not expecting this extra column, which causes all columns to the right to be offset. 

I'm not sure what's the best way to address this, otherwise I may have submitted a pull request. Maybe just extract the season out from the end of the url (e.g. `2018` from "https://www.basketball-reference.com/leagues/NBA_2018.html")?

**Comment by abresler** [comment]
Install the newest version
