### ISSUE TITLE
nbastatR not running on Digital Ocean Droplet

### ISSUE THREAD

**Issue by scotthorvath** [abresler/nbastatR#18]
Hi Alex,

Not sure whether this is something related to the way the package works or if it's a Digital Ocean issue.

Have summarised the issue here:

https://www.digitalocean.com/community/questions/r-package-nbastatr-can-t-request-data?answer=48764

Many Thanks

**Comment by abresler** [comment]
This is a digital ocean issue

NBA stats api blocks certain api addresses and header types from accessing
their data, that is what is probably going on here.


----------------------
Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by abresler** [comment]
This is a digital ocean issue probably related to the NBA stats api blocking certain ip addresses and header types, dont know a good fix other than to try running it locally or see if it works on AWS
