### ISSUE TITLE
`digits` function cannot be found

### ISSUE THREAD

**Issue by batpigandme** [abresler/nbastatR#2]
Querying for synergy stats, getting error re "digits function" 
```
iso_syntergy_stats <- get_nba_synergy_stats(table_name = "Isolation",
+                                             include_defense = T,
+                                             include_offense = T,
+                                             type_table = 'player')
Error: could not find function "digits"
```
Tried manually loading the packages one by one in the order in which you have them listed in the `R` sub, but to no avail. Thanks.

**Comment by abresler** [comment]
Sorry that is from the formattable package just making a change but you
need formattable
----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​
On Jan 18, 2016 2:57 PM, "batpigandme" <notifications@github.com> wrote:

Querying for synergy stats, getting error re "digits function"

iso_syntergy_stats <- get_nba_synergy_stats(table_name = "Isolation",
+                                             include_defense = T,
+                                             include_offense = T,
+                                             type_table = 'player')
Error: could not find function "digits"

Tried manually loading the packages one by one in the order in which you
have them listed in the R sub, but to no avail. Thanks.

—
Reply to this email directly or view it on GitHub
<https://github.com/abresler/nbastatR/issues/2>.

**Comment by batpigandme** [comment]
Awesome– works perfectly now.
