### ISSUE TITLE
I have some errors when I install the library

### ISSUE THREAD

**Issue by TheRabbot17** [abresler/nbastatR#22]
When I install the library with this command:
devtools::install_github("abresler/nbastatR", upgrade = TRUE, force = TRUE, dependencies = TRUE)

The final response is that:
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

And then, with some functions I have some problems. Any idea how can I install properly the library?

**Comment by abresler** [comment]
Sorry I really don't know what your issue is
