### ISSUE TITLE
synergy() not working

### ISSUE THREAD

**Issue by Henryjean** [abresler/nbastatR#23]
When I try to run the synergy example:

`synergy(seasons = 2019, result_types = c("player", "team"), season_types = c("Regular Season"), set_types = "offensive", categories = c("Transition", "Isolation", "PRBallHandler", "PRRollman", "Postup",  "Spotup", "Handoff", "Cut", "OffScreen", "OffRebound", "Misc"), results = 500, assign_to_environment = TRUE, return_wide = F, return_message = TRUE)`

I get the following error: Error in eval(lhs, parent, parent) : object 'types' not found

**Comment by abresler** [comment]
Install the newest version
