### ISSUE TITLE
Synergy(season_types = c("Playoffs")) not working

### ISSUE THREAD

**Issue by Henryjean** [abresler/nbastatR#26]
Despite adding  "Playoffs" to season_types, synergy() will only pull regular season data.

**Comment by abresler** [comment]
Again, this is not the package this is the NBA not releasing the data as of now, if they ever do.

**Comment by Henryjean** [comment]
Maybe i'm misunderstanding because the function does retrieve the data for the regular season. 

Just not the postseason 

I'm referring specifically to this data: https://stats.nba.com/players/isolation/

**Comment by abresler** [comment]
Again, the way this calls the data it does not exist.  

https://stats-prod.nba.com/wp-json/statscms/v1/synergy/player/?category=isolation&season=2018&seasonType=Post&names=offensive&limit=500

The NBA may have changed their query and right now I am not modifying the package so if you need this data I recommend you write your own function

**Comment by ssal23** [comment]
Quick question, I saw you said above that the NBA doesn't release the playoff data to synergy , but when I'm on synergy's platform there is playoff data, so is this an issue w the current iteration of  package?
 Regardless, thanks for making this package public, it's super useful and I appreciate it
