### ISSUE TITLE
seasons_rosters failed in 2015 and 2016

### ISSUE THREAD

**Issue by TheRabbot17** [abresler/nbastatR#28]
When I execute this code:

````
library(nbastatR)
library(future)
library(openxlsx)
library(dplyr)
plan(multiprocess) 

for (iter in 2004:2016) {
  rosters = seasons_rosters(iter)
  openxlsx::write.xlsx(rosters, paste0('rosters-', iter, '.xlsx'))
}
````

it's works in years 2004-2014 but then in the last two years failed with this type of error:

> Error in open.connection(con, "rb") : Send failure: Connection was reset

Any idea of how can i execute this function properly?

**Comment by abresler** [comment]
The function is vectorized to acquire those seasons 

```
library(nbastatR)
library(tidyverse)
d <- seasons_rosters(seasons = 2004:2016)
```
