### ISSUE TITLE
Issues with players_tables()

### ISSUE THREAD

**Issue by jestarr** [abresler/nbastatR#31]
I'm getting an error when running players_tables().  Looks like the NBA Player Table JSON has not updated the Active player list.  

I ran the following and got this error

```
library(tidyverse)
library(nbastatR)


df_players <- nba_players()
#> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows
#> [1711, 3160, 4334, 4340].

player_ids <- df_players %>% filter(yearSeasonLast == 2018) %>% pull(idPlayer)
players_tables(player_ids = player_ids %>% sample(5), tables = "passes", modes = "Totals")
#> Assigning NBA player dictionary to df_dict_nba_players to your environment
#> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows
#> [1711, 3160, 4334, 4340].
#> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows
#> [1711, 3160, 4334, 4340].
#> Acquiring Lou Williams 2019 Regular Season Base passes Totals data
#> Acquiring Wesley Matthews 2019 Regular Season Base passes Totals data
#> Acquiring Jonas Valanciunas 2019 Regular Season Base passes Totals data
#> Acquiring Dewayne Dedmon 2019 Regular Season Base passes Totals data
#> Acquiring Amile Jefferson 2019 Regular Season Base passes Totals data
#> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
#> `dateGameLastPlayed`
#> Warning: Unknown columns: `typeMeasure`
#> Joining, by = "idPlayerPasserPassTo"
#> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
#> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
#> Warning: Unknown columns: `idLeague`
#> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
#> `segmentSeason`, `rangeDaysRest`
#> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
#> `dateGameLastPlayed`
#> Warning: Unknown columns: `typeMeasure`
#> Joining, by = "idPlayerPasserPassTo"
#> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
#> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
#> Warning: Unknown columns: `idLeague`
#> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
#> `segmentSeason`, `rangeDaysRest`
#> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
#> `dateGameLastPlayed`
#> Warning: Unknown columns: `typeMeasure`
#> Joining, by = "idPlayerPasserPassTo"
#> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
#> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
#> Warning: Unknown columns: `idLeague`
#> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
#> `segmentSeason`, `rangeDaysRest`
#> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
#> `dateGameLastPlayed`
#> Warning: Unknown columns: `typeMeasure`
#> Joining, by = "idPlayerPasserPassTo"
#> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
#> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
#> Warning: Unknown columns: `idLeague`
#> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
#> `segmentSeason`, `rangeDaysRest`
#> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
#> `dateGameLastPlayed`
#> Warning: Unknown columns: `typeMeasure`
#> Joining, by = "idPlayerPasserPassTo"
#> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
#> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
#> Warning: Unknown columns: `idLeague`
#> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
#> `segmentSeason`, `rangeDaysRest`
#> `by` required, because the data sources have no common variables
```

**Comment by abresler** [comment]
Works fine for me, try reinstalling the package.

```
players_tables(
  player_ids = c(201936L, 1627735L, 1627781L, 1627855L, 203093L),
  tables = "passes",
  modes = "Totals"
)
```

<img width="577" alt="Screen Shot 2019-06-23 at 3 17 32 PM" src="https://user-images.githubusercontent.com/740564/59980897-0b7a2f00-95ca-11e9-9930-9e8cb0433ad7.png">

**Comment by jocelyndal** [comment]
> 
> 
> I'm getting an error when running players_tables(). Looks like the NBA Player Table JSON has not updated the Active player list.
> 
> I ran the following and got this error
> 
> ```
> library(tidyverse)
> library(nbastatR)
> 
> 
> df_players <- nba_players()
> #> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows
> #> [1711, 3160, 4334, 4340].
> 
> player_ids <- df_players %>% filter(yearSeasonLast == 2018) %>% pull(idPlayer)
> players_tables(player_ids = player_ids %>% sample(5), tables = "passes", modes = "Totals")
> #> Assigning NBA player dictionary to df_dict_nba_players to your environment
> #> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows
> #> [1711, 3160, 4334, 4340].
> #> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows
> #> [1711, 3160, 4334, 4340].
> #> Acquiring Lou Williams 2019 Regular Season Base passes Totals data
> #> Acquiring Wesley Matthews 2019 Regular Season Base passes Totals data
> #> Acquiring Jonas Valanciunas 2019 Regular Season Base passes Totals data
> #> Acquiring Dewayne Dedmon 2019 Regular Season Base passes Totals data
> #> Acquiring Amile Jefferson 2019 Regular Season Base passes Totals data
> #> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
> #> `dateGameLastPlayed`
> #> Warning: Unknown columns: `typeMeasure`
> #> Joining, by = "idPlayerPasserPassTo"
> #> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
> #> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
> #> Warning: Unknown columns: `idLeague`
> #> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
> #> `segmentSeason`, `rangeDaysRest`
> #> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
> #> `dateGameLastPlayed`
> #> Warning: Unknown columns: `typeMeasure`
> #> Joining, by = "idPlayerPasserPassTo"
> #> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
> #> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
> #> Warning: Unknown columns: `idLeague`
> #> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
> #> `segmentSeason`, `rangeDaysRest`
> #> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
> #> `dateGameLastPlayed`
> #> Warning: Unknown columns: `typeMeasure`
> #> Joining, by = "idPlayerPasserPassTo"
> #> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
> #> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
> #> Warning: Unknown columns: `idLeague`
> #> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
> #> `segmentSeason`, `rangeDaysRest`
> #> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
> #> `dateGameLastPlayed`
> #> Warning: Unknown columns: `typeMeasure`
> #> Joining, by = "idPlayerPasserPassTo"
> #> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
> #> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
> #> Warning: Unknown columns: `idLeague`
> #> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
> #> `segmentSeason`, `rangeDaysRest`
> #> Warning: Unknown columns: `orderSort`, `namePlayerLastFirst`,
> #> `dateGameLastPlayed`
> #> Warning: Unknown columns: `typeMeasure`
> #> Joining, by = "idPlayerPasserPassTo"
> #> Warning: Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`
> #> Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")
> #> Warning: Unknown columns: `idLeague`
> #> Warning: Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`,
> #> `segmentSeason`, `rangeDaysRest`
> #> `by` required, because the data sources have no common variables
> ```

i have the same issues , how do you resolve it ?
thanks
