### ISSUE TITLE
Is there a way to pull the Play-by-Play table from bb ref?

### ISSUE THREAD

**Issue by lewispipkin** [abresler/nbastatR#34]
I want to pull the results of this table for each player: https://www.basketball-reference.com/players/a/walkerke02.html#all_pbp

Is this table a part of the result of one of the commands in this package? Thanks!

**Comment by lewispipkin** [comment]
Whoops, messed up the link: https://www.basketball-reference.com/players/w/walkeke02.html#all_pbp

**Comment by abresler** [comment]
I am not adding features to the package right now but you can use the play-by-play data from the nba if you want that.
