### ISSUE TITLE
Closest_defender_ranges inteams_players_stat

### ISSUE THREAD

**Issue by ssal23** [abresler/nbastatR#35]
Cannot seem to get any of the data with the specific closest defender ranges. Issues like this: Acquiring all player PerGame shots Base split tables for the 2018-19 season
Missing CloseDefDistRange in dictionary

**Comment by abresler** [comment]
Can you produce the code you are trying to run

**Comment by ssal23** [comment]
b<- teams_players_stats(seasons = 2018, types=c("team"), tables=c("general"), measures = c("Base"), modes=c("Totals"), starters_bench = c("Bench"))

This is just an example. I have also tried extracting these for types = c("player"), and multiple other combos.

**Comment by ssal23** [comment]
This is my most recent problem, which is getting bench stats. I don't have the scripts for the closest defender issues, but I was just not able to get any results with any combination of CloseDefDistRange not being NA.

**Comment by ssal23** [comment]
Also, Right now this is also an issue > library(nbastatR)
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/nbastatR/help/nbastatR.rdb' is corrupt

**Comment by ssal23** [comment]
Not sure if it is on my end, but just wanted to give you a heads up. Thank you!

**Comment by abresler** [comment]
Install the newest version
