### ISSUE TITLE
bref_bios

### ISSUE THREAD

**Issue by peterJslade** [abresler/nbastatR#36]
There seems to be a bug in the bref_bios function.  Here is my code:

library(nbastatR)
bref_bios("Kyle Lowry")[[6]]
bref_bios("Kawhi Leonard")[[6]]
bref_bios(c("Michael Jordan", "Kobe Bryant")[[6]]

all the bio information is for Kyle Lowry (or whatever the first bio you search for).  This doesn't seem to be the case for other elements of the tibble -- just the sixth.  Any help or possible workarounds are appreciated!

**Comment by abresler** [comment]
This works for me

```
library(nbastatR)
library(tidyverse)
d <- bref_bios("Kyle Lowry")
d %>% select(6) %>%
  unnest()
```

<img width="580" alt="Screen Shot 2019-07-24 at 5 59 57 PM" src="https://user-images.githubusercontent.com/740564/61831804-03b5e080-ae3d-11e9-8670-666fae5d1ca6.png">

**Comment by peterJslade** [comment]
Thanks for the quick response.  Yes, that code works.  My issue occurs when you use bref_bios to search for more than one player.  For example, if I run `bref_bios(players=c("Kyle Lowry", "Kawhi Leonard"))[[6]]` then I get Kyle Lowry's information repeated twice, as opposed to Kyle Lowry and Kawhi Leonard.

**Comment by abresler** [comment]
I will take a look


----------------------
Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by abresler** [comment]
It had to do with memoisation, install the newest version

**Comment by peterJslade** [comment]
Thanks for looking at this.  Memoisation makes sense as the issue.  Though, I'm still having the same issue with the new version -- nbastatR_0.1.12031.
