### ISSUE TITLE
objects getNodeSet and xmlRoot are not exported by namespace:XML

### ISSUE THREAD

**Issue by alecfwilson** [abresler/nbastatR#4]
> all_salaries <- 
> -   get_all_team_salaries()
>   Joining by: "slug.team"
>   Error: objects ‘getNodeSet’, ‘xmlRoot’ are not exported by 'namespace:XML'

I've dug into this a decent amount, and tried assigning it in my namespace per StackOverflow, but am told that there is no binding for xmlRoot. I'm not well versed in R, so I'm having trouble sorting out what the issue is.

**Comment by abresler** [comment]
This function has been removed
