### ISSUE TITLE
Errors starting on 11/7/2019

### ISSUE THREAD

**Issue by jyablonski** [abresler/nbastatR#40]
Hi, i've been using the package for the past 2 weeks to pull gamelogs from this season and have updated it every morning without any issues.  This morning I tried using it and my code didn't execute and I got the following errors.  

When I try running the seasons_schedule function I get this error:
Error: Column `dateGame` is unknown
In addition: Warning message:
In for (i in seq_along(ix)) { :
  closing unused connection 4 (https://stats.nba.com/stats/leaguegamelog?Counter=1000&Season=2019-20&Direction=DESC&LeagueID=00&PlayerOrTeam=T&SeasonType=Regular%20Season&Sorter=DATE)

And when I try running the game_logs function I get this error:
Error in open.connection(con, "rb") : Send failure: Connection was reset

Is anyone able to reproduce these issues?

**Comment by abresler** [comment]
NBA may have massively changed their API which likely nukes this package unfortunately.

I will look into but I am not in a position to refactor this package right now.

**Comment by abresler** [comment]
Install the newest version
