### ISSUE TITLE
boxscores

### ISSUE THREAD

**Issue by Ollstar** [abresler/nbastatR#41]
Since Nov 7 2019,
g = box_scores(game_ids = c(21700002), box_score_types = c("Traditional"), result_types = c("player"), join_data = TRUE, assign_to_environment = TRUE, return_message = TRUE)

The code above produces these errors:
Warning messages:
1: In for (ii in 1L:length(res)) { :
  closing unused connection 4 (https://stats.nba.com/stats/boxscoretraditionalv2?SeasonType=&LeagueID=00&Season=&IsOnlyCurrentSeason=&PlayerID=&TeamID=&GameID=0021700002&ContextMeasure=&PlayerPosition=&DateFrom=&DateTo=&GameSegment=&LastNGames=&Location=&Month=&OpponentTeamID=&Outcome=&SeasonSegment=&VSConference=&VSDivision=&RookieYear=&Period=&StartPeriod=0&EndPeriod=12&StartRange=0&EndRange=12&RangeType=1&runType=)
2: Unknown or uninitialised column: 'typeResult'. 
3: Unknown or uninitialised column: 'typeResult'. 

The nba api seems to have changed. I found for another project that they have added a Referer to headers. And setting 'Referer': 'https://stats.nba.com/', was a workaround. 
headers = {
    'Host': 'stats.nba.com',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
    'Accept': 'application/json, text/plain, */*',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
}

**Comment by delt87** [comment]
@Ollstar were you able to get any of the functions from this package to work?  How did you add the header reference?  I see that the nba_api package for python has been updated to include the new header reference but I don't see how I can include the header into any of the functions in this package.

**Comment by Ollstar** [comment]
The endpoints in this package no longer work due to the recent changes. If you change them to the ones that nba api uses and has shown to work then you might be able to refactor a fork of this project to get it to work. Alternatively, using nba_api may be the best option if the creator of nbastatR doesn't intend a new patch.

**Comment by abresler** [comment]
Reinstall
