### ISSUE TITLE
players_tables function issues

### ISSUE THREAD

**Issue by jocelyndal** [abresler/nbastatR#42]
hi ,
I try to use the function players_tables with the exemple but i have errors when i run it :
`Assigning NBA player dictionary to df_dict_nba_players to your environment
Expected 2 pieces. Missing pieces filled with `NA` in 4 rows [1758, 3250, 4451, 4457].Acquiring Joe Harris 2019 Regular Season Base year over year PerGame data
Acquiring Caris LeVert 2019 Regular Season Base year over year PerGame data
Acquiring Joe Harris 2019 Regular Season Base passes PerGame data
Acquiring Caris LeVert 2019 Regular Season Base passes PerGame data
Acquiring Joe Harris 2019 Regular Season Base game splits PerGame data
Acquiring Caris LeVert 2019 Regular Season Base game splits PerGame data
Acquiring Joe Harris 2019 Regular Season Advanced year over year PerGame data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Caris LeVert 2019 Regular Season Advanced year over year PerGame data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Joe Harris 2019 Regular Season Advanced passes PerGame data
Acquiring Caris LeVert 2019 Regular Season Advanced passes PerGame data
Acquiring Joe Harris 2019 Regular Season Advanced game splits PerGame data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Caris LeVert 2019 Regular Season Advanced game splits PerGame data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Joe Harris 2019 Regular Season Base year over year Totals data
Acquiring Caris LeVert 2019 Regular Season Base year over year Totals data
Acquiring Joe Harris 2019 Regular Season Base passes Totals data
Acquiring Caris LeVert 2019 Regular Season Base passes Totals data
Acquiring Joe Harris 2019 Regular Season Base game splits Totals data
Acquiring Caris LeVert 2019 Regular Season Base game splits Totals data
Acquiring Joe Harris 2019 Regular Season Advanced year over year Totals data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Caris LeVert 2019 Regular Season Advanced year over year Totals data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Joe Harris 2019 Regular Season Advanced passes Totals data
Acquiring Caris LeVert 2019 Regular Season Advanced passes Totals data
Acquiring Joe Harris 2019 Regular Season Advanced game splits Totals data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Acquiring Caris LeVert 2019 Regular Season Advanced game splits Totals data
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
Missing sp_work_OFF_RATING in dictionary
Missing sp_work_DEF_RATING in dictionary
Missing sp_work_NET_RATING in dictionary
Missing E_TOV_PCT in dictionary
Missing PACE_PER40 in dictionary
Missing sp_work_PACE in dictionary
Missing E_OFF_RATING_RANK in dictionary
Missing sp_work_OFF_RATING_RANK in dictionary
Missing E_DEF_RATING_RANK in dictionary
Missing sp_work_DEF_RATING_RANK in dictionary
Missing E_NET_RATING_RANK in dictionary
Missing sp_work_NET_RATING_RANK in dictionary
Missing E_TOV_PCT_RANK in dictionary
Missing E_USG_PCT_RANK in dictionary
Missing E_PACE_RANK in dictionary
Missing sp_work_PACE_RANK in dictionary
NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`Unknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `typeMeasure`Joining, by = "idPlayerPasserPassTo"Unknown columns: `orderSort`, `idLeague`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "numberTable", "slugSeason", "idPlayer", "idTeam")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`NAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueNAs introduits lors de la conversion automatiqueUnknown columns: `orderSort`, `namePlayerLastFirst`, `dateGameLastPlayed`Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed`Joining, by = c("typeSeason", "modeSearch", "typeMeasure", "numberTable", "slugSeason")Unknown columns: `idLeague`Unknown columns: `resultGame`, `locationGame`, `nameSeasonMonth`, `segmentSeason`, `rangeDaysRest
`Erreur : `by` required, because the data sources have no common variables`

What is the problem ?
Thank you !

**Comment by abresler** [comment]
Install the newest version
