### ISSUE TITLE
seasons_schedule error

### ISSUE THREAD

**Issue by mckiernan7** [abresler/nbastatR#43]
seasons_schedule() is returning the following error. Function still returns a dataframe with columns 
"typeSeason", "slugSeason", "idGame", "dateGame", "slugMatchup", "slugTeamWinner", "slugTeamLoser", and "numberGameDay"

> schedule1819 = seasons_schedule()

Acquiring NBA basic team game logs for the 2018-19 Regular Season
Joining, by = c("slugTeam", "dateGame", "idTeam", "yearSeason")Warning messages:
1: Unknown columns: `orderSort`, `idLeague`, `namePlayerLastFirst`, `dateGameLastPlayed` 
2: All elements of `...` must be named.
Did you want `dataTables = c(typeSeason, dateGame, idGame, numberGameTeamSeason, nameTeam, 
    idTeam, isB2B, isB2BFirst, isB2BSecond, locationGame, slugMatchup, 
    slugTeam, countDaysRestTeam, countDaysNextGameTeam, slugOpponent, 
    slugTeamWinner, slugTeamLoser, outcomeGame, isWin, fgmTeam, 
    fgaTeam, pctFGTeam, fg3mTeam, fg3aTeam, pctFG3Team, pctFTTeam, 
    hasVideo, fg2mTeam, fg2aTeam, pctFG2Team, minutesTeam, ftmTeam, 
    ftaTeam, orebTeam, drebTeam, trebTeam, astTeam, stlTeam, 
    blkTeam, tovTeam, pfTeam, ptsTeam, plusminusTeam, urlTeamSeasonLogo)`? 
3: `cols` is now required.
Please use `cols = c(dataTables)` 
4: Unknown columns: `idSeason`

**Comment by abresler** [comment]
works fine for me try reinstalling
