### ISSUE TITLE
bref_players_stats() not pulling all players from www.basketball-reference.com

### ISSUE THREAD

**Issue by spelk24** [abresler/nbastatR#44]
Some players are missing from the bref_players_stats() scrape. For 2020 ("totals"), it should return 466 players, but only returns 456. Missing players include: Kevin Porter Jr, P.J. Washington, Dennis Smith Jr., Kevin Knox, Marcus Morris, and others.

Reference:  https://www.basketball-reference.com/leagues/NBA_2020_totals.html

**Comment by abresler** [comment]
reinstall
