### ISSUE TITLE
Errors starting on 1/22/2020

### ISSUE THREAD

**Issue by jyablonski** [abresler/nbastatR#46]
Hi I started getting some errors while running certain functions yesterday and I was wondering if these are reproducible issues for anyone else.  I tried reinstalling the package but it didn't seem to help.  I listed the 4 functions i normally use below and the error i got with each of them.

`schedule <- seasons_schedule(seasons=2020, season_type="Regular Season")`
Error: Column `dateGame` is unknown

`gameLogs <- game_logs(seasons=2020, league="NBA", result_types="player", season_types="Regular Season")`
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback

`teamStats <- bref_teams_stats(seasons = 2020)`
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback

`injuryDB <- bref_injuries()`
Error in eval_tidy(pair$lhs, env = default_env) : 
  object 'slugPlayerBREF' not found

I did have some functions that still worked though:
```
nba_insider_salaries()
dictionary_bref_players()
```

**Comment by delt87** [comment]
I've been following the same issue as reported in the nba_api for Python and the issues seems to be related to the fact that NBA API headers have changed (again).  The same issue is happening in the `nbaTools` package and I posted an issue in that package along with the fix below.  Adding the following fields to the headers call for the `nbaTools` package returned the expected output so I assume doing the same thing for this package will correct the hanging calls to the NBA API.

```
    'x-nba-stats-origin' = 'stats',
    'x-nba-stats-token' = 'true'
```

**Potentially working NBA headers (I haven't yet been able to manually test the NBA API functions for this package):**
```
  'NBA' = list(
    'Accept' = 'application/json, text/plain, */*',
    'Accept-Language' = 'en-US,en;q=0.8,af;q=0.6',
    'Referer' = 'http://stats.nba.com/%referer%/',
    'User-Agent' = paste('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)',
                         'AppleWebKit/537.36 (KHTML, like Gecko)',
                         'Chrome/67.0.3396.99 Safari/537.36'),
    'x-nba-stats-origin' = 'stats',
    'x-nba-stats-token' = 'true'
  ) 
```
I'm not familiar with how GitHub works as far as making changes to other people's work. I figured if I made you aware of the change in the headers and the potential fix, it would be easier for you to update the package on your end with the new headers.

**Comment by emmett4** [comment]
I have also had problems with game_logs(), which runs without ever completing.

Please help!

**Comment by abresler** [comment]
> I've been following the same issue as reported in the nba_api for Python and the issues seems to be related to the fact that NBA API headers have changed (again). The same issue is happening in the `nbaTools` package and I opened an issue in that package along with the fix below. Adding the following fields to the headers call for the `nbaTools` package returned the expected output so I assume doing the same thing for this package will correct the hanging calls to the NBA API.
> 
> ```
>     'x-nba-stats-origin' = 'stats',
>     'x-nba-stats-token' = 'true'
> ```

THANKS!!!

**Comment by abresler** [comment]
Reinstall the newest version

**Comment by emmett4** [comment]
Thank you, and thank you for your nbastats package, its absolutely awesome!

Emmett
