### ISSUE TITLE
Can´t install package

### ISSUE THREAD

**Issue by gonzalorondinone** [abresler/nbastatR#49]
Dear all, 

I´ve been trying to install but 

> install.packages("nbastatR")
Warning in install.packages :
  package ‘nbastatR’ is not available (for R version 3.6.2)

Do you know what I have to do?

**Comment by lewispipkin** [comment]
Hey, I’m not the developer but just run this:

library(devtools)
install_github(“abresler/nbastatR”)
library(nbastatR)

**Comment by gonzalorondinone** [comment]
Thanks! I tryed but I got this 

Execution halted
ERROR: lazy loading failed for package ‘nbastatR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/nbastatR’
Error: Failed to install 'nbastatR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/n4/yf7ndy852z9390rvwj9b3lb00000gn/T//RtmpcN5Ope/file6a847380b7cd/nbastatR_0.1.1502.tar.gz’ had non-zero exit status

**Comment by gonzalorondinone** [comment]
It is solved. I have updated my OS and reinstalled a couple of packages and now it is working.
