### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by mmw13** [abresler/nbastatR#52]
When I try to install the nbastatR package I get the follwing...

installing` the source package ‘digest’

trying URL 'https://cran.rstudio.com/src/contrib/digest_0.6.25.tar.gz'
Content type 'application/x-gzip' length 145642 bytes (142 KB)
downloaded 142 KB

ERROR: failed to lock directory 'C:/Users/maxwh/Documents/R/win-library/3.6' for modifying
Try removing 'C:/Users/maxwh/Documents/R/win-library/3.6/00LOCK-digest'
Error: Failed to install 'nbastatR' from GitHub:
  (converted from warning) installation of package ‘digest’ had non-zero exit `status

Is there anything I need to do?

**Comment by abresler** [comment]
I need more information than this but it likely has to do with the digest package not being able to install; check the documentation for that package and try again
