### ISSUE TITLE
Package problems

### ISSUE THREAD

**Issue by GShotwell** [abresler/nbastatR#53]
Thanks for the great package, I noticed a few things which you might want to resolve to help people use the package: 

- Specify imports, currently you are importing lots of functions without using the `::` or `@importFrom` structure. This leads to all the scary warnings when loading the package, and also is an invitation for bugs because you're not specifying which namespace you want the function to come from. 
- A number of missing dependencies in the Description file (stringi, rlang, glue)
- Lots of undefined global variables (which can be resolved using the .data$ object from dplyr)
- Test failures 

I'm happy to help with some of the issues if there's an interest, but even if you're not ever planning ton putting this on CRAN, passing CRAN checks is a really good way to improve  how people use the package.

**Comment by abresler** [comment]
Feel free to fork and contribute - this package is not intended for CRAN but thank you for the feedback
