### ISSUE TITLE
Add decimals to timeQuarter in play-by-play with < 1 min left in quarter

### ISSUE THREAD

**Issue by joseremista** [abresler/nbastatR#58]
Is it possible to add the decimal to the timeQuarter column in the output of the play_by_play_v2 function when the play happens with under a minute left in a quarter? I tried making a call to the API and realized that they add the decimal in these situations. Here's an example:

```
library(httr)
library(jsonlite)
library(tidyverse)

test_call <-  GET("http://data.nba.net/prod/v1/20200311/0021900971_pbp_4.json")

data_test <- fromJSON(rawToChar(test_call$content))

pbp_test <- data_test %>%
  pluck("plays") %>%
  as_tibble()

pbp_teste %>%
  filter(str_detect(clock, "00:")) %>%
  select(clock)
```
And the output:

```
[1] "00:51.6" "00:50.1" "00:50.1" "00:50.1" "00:50.1" "00:48.5" "00:38.4" "00:34.3" "00:34.3" "00:32.1" "00:13.5" "00:08.1" "00:04.7" "00:00.0"
```

It would be really helpful for play-by-play data analysis. Thanks in advance!

**Comment by abresler** [comment]
No
