### ISSUE TITLE
Play by Play Substitution Events Question

### ISSUE THREAD

**Issue by micolbrittain** [abresler/nbastatR#59]
This isn't really an issue more of a question. I'm trying to add 10 columns to each row of the play by play data to show the 10 players on the court during each event. I snagged the starters via the traditional box scores 'isStarter' for the specific 'idGame' as a starting point. Then I figured out that 'numberEventMessageType == "8"' is the event # for a substitution.  From there I can run through each column of the players on the court and find which column matches the 'namePlayer1' (the one subing out) and replace it with 'namePlayer2' (the one who is replacing him in the lineup). However it looks like I run into a snag in that there isn't an event row when a subsitution occurs between quarters, or at least from the sample idGames i've been testing it with. I noticed the 'numberEvent' skips some numbers so I assume you filtered out some events in the entire playbyplay log that may not necessarily pertain to a statistical event. I've looked through the code to see where this might be filtered out but I cannot find it. Is it possible to capture all substitution events even if they happen between quarters? Or is that even in the original dataset? 

I'm only a couple weeks into teaching myself R and I'm using what you have created to make this a fun learning experience. Most of my experience with data is SQL based so I've been using your package here to write tables to my localhost SQL to be able to competently manipulate it then going back and looking up how to do it within R studio it's fun stuff. Thanks for sharing this I work a lot with SQL and Power BI and being able to use R script is proving very useful.

**Comment by delt87** [comment]
Since your question pertains more to your code rather than an issue with this package, I recommend you post this question to stackoverflow along with your code. You're more likely to get a response that way. Good luck.
