### ISSUE TITLE
"tidyjson" not available

### ISSUE THREAD

**Issue by jordangalexander** [abresler/nbastatR#6]
ERROR: dependency ‘tidyjson’ is not available for package ‘nbastatR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/nbastatR’
Installation failed: Command failed (1)

--> this is the error I get when running the line:

1 devtools::install_github("abresler/nbastatR")

**Comment by abresler** [comment]
Removing this dependency in re-launch
