### ISSUE TITLE
Trouble trying to access Synergy table.

### ISSUE THREAD

**Issue by awi11s** [abresler/nbastatR#62]
I have been trying to access the synergy table to get pick and roll data for certain players. I have tried to view the table by entering the proper parameters, but still get a warning pertaining to the 'typeResult' column, and no data showing up. Example code:

`synergy(seasons = 2020, result_types = "player", set_types = "offensive", categories = "PRBallHandler")
`

And the warning I get in return is:

`In addition: Warning message:
Unknown or uninitialised column: `typeResult`.`

Any help is appreciated!

**Comment by abresler** [comment]
NBA removed this API
