### ISSUE TITLE
`bref_teams_stats()` not working

### ISSUE THREAD

**Issue by alamine53** [abresler/nbastatR#65]
`bref_teams_stats()` produces the following error: 

"Error: 'by' must be supplied when 'x' and 'y' have no common variables." 

I also tried `teams_annual_stats(season = 2020)` but I get "Timeout was reached:... " All other functions work fine though. 

Appreciate the help!

**Comment by abresler** [comment]
Reinstall the package -- it works for me..

<img width="1776" alt="Screen Shot 2021-01-04 at 10 33 23 AM" src="https://user-images.githubusercontent.com/740564/103551424-512edd80-4e78-11eb-9153-c00848030511.png">
