### ISSUE TITLE
bref_players_stats is not fully working

### ISSUE THREAD

**Issue by HershGupta25** [abresler/nbastatR#67]
It doesnt seem to be pulling the stats for all the games this season. From what I am seeing, it is not collecting data from Dec 31 and Jan 1 of the NBA season. My code is below. 

bref_players_stats(seasons = 2021,tables = c("totals","advanced","per_game"),
                              widen_data = T)

**Comment by abresler** [comment]
You can't specify the tables, follow the function input parameters
