### ISSUE TITLE
box_scores() hangs after ~150 calls

### ISSUE THREAD

**Issue by matthew-hoty** [abresler/nbastatR#68]
I am trying to download historical team + player boxscores for some analysis.  Currently, my approach is to call game_logs() for a specific season, take those game IDs, and then loop through each idGame and call box_scores() with that id to get the data.  The loop will consistently iterate 150 times successfully but on the 151st try, it indefinitely hangs.  Is there a better approach to downloading this data?

**Comment by delt87** [comment]
Looping through gameids is the only way as far as I can tell from using both functions pretty frequently. I would recommend breaking up your scraping over a couple of days / nights since you'll be querying  82 games x 30 teams. NBA won't be too happy letting you hit their endpoints for that much data all at once.

**Comment by hopeful-coder** [comment]
I have the same issue. Trying to get every box score is a nightmare, but I want it!

**Comment by hopeful-coder** [comment]
Follow-up on this. Do you have any recommendations to a "Pause time". Maybe we are using too many calls in a short amount of time.

**Comment by delt87** [comment]
This is not the correct place to ask coding questions. Stackoverflow.com is where you should look. A quick Google search and I found this: https://stackoverflow.com/questions/47780628/using-sys-sleep-to-delay-api-call

**Comment by hopeful-coder** [comment]
Thank you for your reply, delt87. I wasn't asking a coding question. I was asking for specifics related to your "NBA won't be too happy letting you hit their endpoints for that much data all at once." comment. Do you recommend a certain amount of sleep time in between queries or loops to keep the process continuously going? Like OP, I see box_scores() hangs after so many calls, and I would like it to not hang please.

**Comment by abresler** [comment]
If you want the data you need to download the data for each game id.

There arent any magic shortcuts
