### ISSUE TITLE
bref_teams_stats not working

### ISSUE THREAD

**Issue by drewlredding** [abresler/nbastatR#79]
> bref_teams_stats(season=2020,nest_data=F,widen_data=T,assign_to_environment = T)
Parsing https://www.basketball-reference.com/leagues/NBA_2020.html
Warning: Problem with `mutate()` input `gamesBehind1Conference`.
i 1 parsing failure.
row col expected actual
  1  -- a number      —

i Input `gamesBehind1Conference` is ``%>%`(...)`.
Warning: 1 parsing failure.
row col expected actual
  1  -- a number      —

Joining, by = "nameTeam"
Warning: Problem with `mutate()` input `gamesBehind1Conference`.
i 1 parsing failure.
row col expected actual
  1  -- a number      —

i Input `gamesBehind1Conference` is ``%>%`(...)`.
Warning: 1 parsing failure.
row col expected actual
  1  -- a number      —

Joining, by = "nameTeam"
Joining, by = "idRow"
Joining, by = "nameTeam"
Joining, by = "idRow"
Joining, by = "nameTeam"
Error: `by` must be supplied when `x` and `y` have no common variables.
i use by = character()` to perform a cross-join.
Run `rlang::last_error()` to see where the error occurred.
In addition: There were 12 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: Expected 2 pieces. Missing pieces filled with `NA` in 15 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].
2: Expected 2 pieces. Missing pieces filled with `NA` in 15 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].
3: Expected 2 pieces. Missing pieces filled with `NA` in 18 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18].
4: Problem with `mutate()` input `winsTeam`.
i NAs introduced by coercion
i Input `winsTeam` is `winsTeam %>% as.integer()`.
5: In function_list[[k]](value) : NAs introduced by coercion
6: Problem with `mutate()` input `lossesTeam`.
i NAs introduced by coercion
i Input `lossesTeam` is `lossesTeam %>% as.integer()`.
7: In function_list[[k]](value) : NAs introduced by coercion
8: Expected 2 pieces. Missing pieces filled with `NA` in 18 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18].
9: Problem with `mutate()` input `winsTeam`.
i NAs introduced by coercion
i Input `winsTeam` is `winsTeam %>% as.integer()`.
10: In function_list[[k]](value) : NAs introduced by coercion
11: Problem with `mutate()` input `lossesTeam`.
i NAs introduced by coercion
i Input `lossesTeam` is `lossesTeam %>% as.integer()`.
12: In function_list[[k]](value) : NAs introduced by coercion

**Comment by abresler** [comment]
Try the newest version
