### ISSUE TITLE
Pro Sports Transactions functions

### ISSUE THREAD

**Issue by aelhabr** [abresler/nbastatR#8]
I think the Pro Sports Transactions function (e.g. get_nba_pst_transactions()) should substitute spaces in the person's name with "+". For example, get_nba_pst_transaction("Blake Griffin") should change "Blake Griffin" to "Blake+Griffin" under the hood. Otherwise you are likely to get a "Error in open.connection(con, "rb") : HTTP error 400" message.

**Comment by abresler** [comment]
See newest update for fix

**Comment by aelhabr** [comment]
That was quick haha.
