### ISSUE TITLE
ERROR on Installing nbastatR

### ISSUE THREAD

**Issue by Otoliths** [abresler/nbastatR#9]
> devtools::install_github("abresler/nbastatR")
Downloading GitHub repo abresler/nbastatR@master
from URL https://api.github.com/repos/abresler/nbastatR/zipball/master
Installing nbastatR
"F:/PROGRA~2/R/R/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Administrator/AppData/Local/Temp/RtmpMzRDma/devtools1b7863ba192f/abresler-nbastatR-031bc86" --library="F:/Program  \
  Files/R/R/library" --install-tests 

* installing *source* package 'nbastatR' ...
** R
Error in parse(outFile) : 
  invalid multibyte character in parser at line 159
ERROR: unable to collate and parse R files for package 'nbastatR'
* removing 'F:/Program Files/R/R/library/nbastatR'
Installation failed: Command failed (1)

**Comment by abresler** [comment]
This has nothing to do with the package this has to do with your ability to download and install packages.
