### ISSUE TITLE
All Functions just hang

### ISSUE THREAD

**Issue by keithegiles** [abresler/nbastatR#92]
I can't get a single one of these functions to either run or give me an error code. Installation seems to be successful.  But no matter what I do, all the codes start running and hang up forever.  Is this package currently functional? Do I need an API key?  I'd love to use this if possible.

**Comment by abresler** [comment]
That isn't a reproducible example.

This works just fine for me.

```nbastatR::game_logs(seasons = 2022, season_types = "Pre Season")```

Try reinstalling otherwise I dont know what to tell you
